@startuml
actor customer
actor customer
participant checks_system_discount_of_available
activate checks_system_discount_of_available
participant a_offers_of_discount_list
checks_system_discount_of_available -> a_offers_of_discount_list: display()
activate a_offers_of_discount_list
deactivate a_offers_of_discount_list
customer -> checks_system_discount_of_available: choose_a specific discount offer()
activate customer
participant details
checks_system_discount_of_available -> details: offer()
activate details
deactivate details
customer -> checks_system_discount_of_available: click_on add to basket button()
participant checks_system_discount_of_available_checks_system_discount_of_available
checks_system_discount_of_available -> checks_system_discount_of_available_checks_system_discount_of_available: offers()
activate checks_system_discount_of_available_checks_system_discount_of_available
deactivate checks_system_discount_of_available_checks_system_discount_of_available
@enduml
